# .github/workflows/notify-devin-via-webhook.yml
name: Ask Devin to update documents via Slack Webhook

on:
  push:
    paths-ignore:
      - 'docs-devin/**'
    branches:
      - v2

jobs:
  prompt-devin:
    runs-on: ubuntu-latest
    steps:
      - name: Send prompt via Incoming Webhook
        run: |
          SLACK_TEXT="<@U08PYJ5B9LK> "

          SLACK_TEXT+="bufferings/ecspresso リポジトリのv2ブランチが対象です。"
          SLACK_TEXT+=".github/workflows/devin/gen-doc-instruction.md に従ってPRを作成してください。"
          SLACK_TEXT+="指示ファイルに従って作業をする以外には何も読み込まないでください。\n"

          payload="{\"text\":\"${SLACK_TEXT//\"/\\\"}\"}"

          curl -X POST -H 'Content-Type: application/json' \
               --data "$payload" \
               "${{ secrets.SLACK_DEVIN_CALLER_WEBHOOK_URL }}"
